with deduped as (
    select *,
        row_number() over (
            partition by company_number, end_date
            order by loaded_at desc
        ) as rn
    from {{ source('src_tables', 'src_filings') }}
)

select
    pl_turnover::NUMERIC,
    pl_tax_on_profit_loss::NUMERIC,
    pl_salaries::NUMERIC,
    pl_retained_profits::NUMERIC,
    pl_profit_before_tax::NUMERIC,
    pl_other_op_income::NUMERIC,
    pl_other_interest_income::NUMERIC,
    pl_operating_profit_loss::NUMERIC,
    pl_net_profit_loss::NUMERIC,
    pl_interest_payable::NUMERIC,
    pl_gross_profit_loss::NUMERIC,
    pl_distribution_costs::NUMERIC,
    pl_depreciation_ppe::NUMERIC,
    pl_cost_of_sales::NUMERIC,
    pl_comprehensive_income::NUMERIC,
    pl_audit_fees::NUMERIC,
    pl_administrative_expenses::NUMERIC,
    notes_wages_and_salaries::NUMERIC,
    notes_social_security_costs::NUMERIC,
    notes_pension_other_costs::NUMERIC,
    notes_pension_defined_contrib::NUMERIC,
    notes_government_grants_payable::NUMERIC,
    notes_government_grant_income::NUMERIC,
    notes_fees_non_audit::NUMERIC,
    notes_employee_count::TEXT,
    notes_director_advance_made::NUMERIC,
    notes_director_advance_balance::NUMERIC,
    notes_audit_fees_expenses::NUMERIC,
    loaded_at::TIMESTAMPTZ,
    eq_share_capital::NUMERIC,
    eq_retained_earnings::NUMERIC,
    eq_pl_affecting_equity::NUMERIC,
    eq_dividends_paid::NUMERIC,
    eq_comprehensive_income::NUMERIC,
    {{ target.schema }}.cast_to_date(end_date) as end_date,
    EXTRACT(YEAR FROM {{ target.schema }}.cast_to_date(end_date))::integer AS end_date_year,
    company_number::TEXT,
    cf_taxes_paid_operating::NUMERIC,
    cf_tax_on_profit_loss::NUMERIC,
    cf_purchase_ppe::NUMERIC,
    cf_proceeds_sales_ppe::NUMERIC,
    cf_net_interest_investing::NUMERIC,
    cf_net_change_cash::NUMERIC,
    cf_net_cf_operating::NUMERIC,
    cf_net_cf_investing::NUMERIC,
    cf_net_cf_financing::NUMERIC,
    cf_net_cash_generated_from_operations::NUMERIC,
    cf_interest_expense_on_bank_overdrafts::NUMERIC,
    cf_dividends_paid_financing::NUMERIC,
    cf_change_inventories::NUMERIC,
    cf_change_debtors::NUMERIC,
    cf_change_creditors::NUMERIC,
    cf_cash_bank_on_hand_at_beginning_of_year::NUMERIC,
    cf_cash_bank_on_hand::NUMERIC,
    bs_trade_debtors_non_current::NUMERIC,
    bs_trade_debtors_current::NUMERIC,
    bs_trade_creditors_non_current::NUMERIC,
    bs_trade_creditors_current::NUMERIC,
    bs_total_borrowings::NUMERIC,
    bs_total_assets_less_curr_liab::NUMERIC,
    bs_total_assets::NUMERIC,
    bs_stock::NUMERIC,
    bs_shareholders_equity::NUMERIC,
    bs_retained_earnings::NUMERIC,
    bs_pension_unpaid_non_current::NUMERIC,
    bs_pension_unpaid_current::NUMERIC,
    bs_other_investments::NUMERIC,
    bs_net_current_assets_liab::NUMERIC,
    bs_net_assets::NUMERIC,
    bs_loans_from_directors::NUMERIC,
    bs_liabilities::NUMERIC,
    bs_investments::NUMERIC,
    bs_investment_property_fv::NUMERIC,
    bs_investment_property::NUMERIC,
    bs_inv_subsidiaries_fv::NUMERIC,
    bs_inv_subsidiaries::NUMERIC,
    bs_inv_joint_ventures::NUMERIC,
    bs_inv_group_undertakings::NUMERIC,
    bs_inv_group_part_interests::NUMERIC,
    bs_inv_fixed_assets::NUMERIC,
    bs_inv_associates::NUMERIC,
    bs_intangible_assets::NUMERIC,
    bs_government_grants_payable::NUMERIC,
    bs_fixed_assets::NUMERIC,
    bs_disposals_inv_prop_fv::NUMERIC,
    bs_debtors_non_current::NUMERIC,
    bs_debtors_current::NUMERIC,
    bs_current_assets::NUMERIC,
    bs_current_asset_investments::NUMERIC,
    bs_creditors_non_current::NUMERIC,
    bs_creditors_current::NUMERIC,
    bs_cash::NUMERIC,
    bs_calledup_share_capital::NUMERIC,
    bs_bank_overdrafts_non_current::NUMERIC,
    bs_bank_overdrafts_current::NUMERIC,
    bs_bank_overdrafts::NUMERIC,
    bs_accrued_liabilities::NUMERIC
from deduped
where rn = 1