

WITH turnover_history AS (
    SELECT
        *,
        LAG(pl_turnover)              OVER (PARTITION BY company_number ORDER BY end_date) AS pl_turnover_prev,
        LAG(pl_operating_profit_loss) OVER (PARTITION BY company_number ORDER BY end_date) AS pl_operating_profit_loss_prev,
        LAG(pl_net_profit_loss)       OVER (PARTITION BY company_number ORDER BY end_date) AS pl_net_profit_loss_prev

    FROM  {{ ref('fct_filings') }}
),
with_growth AS (
    SELECT *,
           ROUND((pl_turnover - pl_turnover_prev) / pl_turnover_prev * 100, 2)                                        AS turnover_growth_pct,
           ROUND((pl_operating_profit_loss - pl_operating_profit_loss_prev) / pl_operating_profit_loss_prev * 100, 2) AS operating_profit_growth_pct,
           ROUND((pl_net_profit_loss - pl_net_profit_loss_prev) / pl_net_profit_loss_prev * 100, 2)                   AS net_profit_growth_pct
    FROM turnover_history
)
SELECT
    -- all original columns
    company_number,
    end_date,
    loaded_at,
    pl_turnover,
    pl_gross_profit_loss,
    pl_operating_profit_loss,
    pl_profit_before_tax,
    pl_tax_on_profit_loss,
    pl_net_profit_loss,
    pl_retained_profits,
    pl_comprehensive_income,
    pl_cost_of_sales,
    pl_distribution_costs,
    pl_administrative_expenses,
    pl_other_op_income,
    pl_other_interest_income,
    pl_interest_payable,
    pl_salaries,
    pl_depreciation_ppe,
    pl_audit_fees,
    bs_total_assets,
    bs_fixed_assets,
    bs_intangible_assets,
    bs_current_assets,
    bs_cash,
    bs_debtors_current,
    bs_debtors_non_current,
    bs_stock,
    bs_creditors_current,
    bs_creditors_non_current,
    bs_net_current_assets_liab,
    bs_total_assets_less_curr_liab,
    bs_liabilities,
    bs_net_assets,
    bs_shareholders_equity,
    bs_retained_earnings,
    bs_calledup_share_capital,
    bs_total_borrowings,
    bs_bank_overdrafts,
    bs_bank_overdrafts_current,
    bs_bank_overdrafts_non_current,
    bs_trade_debtors_current,
    bs_trade_debtors_non_current,
    bs_trade_creditors_current,
    bs_trade_creditors_non_current,
    bs_loans_from_directors,
    bs_investments,
    bs_investment_property,
    bs_investment_property_fv,
    bs_inv_subsidiaries,
    bs_inv_subsidiaries_fv,
    bs_inv_associates,
    bs_inv_joint_ventures,
    bs_inv_group_undertakings,
    bs_inv_group_part_interests,
    bs_inv_fixed_assets,
    bs_other_investments,
    bs_current_asset_investments,
    bs_pension_unpaid_current,
    bs_pension_unpaid_non_current,
    bs_government_grants_payable,
    bs_accrued_liabilities,
    bs_disposals_inv_prop_fv,
    cf_net_cf_operating,
    cf_net_cf_investing,
    cf_net_cf_financing,
    cf_net_change_cash,
    cf_net_cash_generated_from_operations,
    cf_taxes_paid_operating,
    cf_tax_on_profit_loss,
    cf_purchase_ppe,
    cf_proceeds_sales_ppe,
    cf_net_interest_investing,
    cf_interest_expense_on_bank_overdrafts,
    cf_dividends_paid_financing,
    cf_change_inventories,
    cf_change_debtors,
    cf_change_creditors,
    cf_cash_bank_on_hand,
    cf_cash_bank_on_hand_at_beginning_of_year,
    eq_share_capital,
    eq_retained_earnings,
    eq_pl_affecting_equity,
    eq_dividends_paid,
    eq_comprehensive_income,
    notes_wages_and_salaries,
    notes_social_security_costs,
    notes_pension_other_costs,
    notes_pension_defined_contrib,
    notes_government_grants_payable,
    notes_government_grant_income,
    notes_fees_non_audit,
    notes_employee_count,
    notes_director_advance_made,
    notes_director_advance_balance,
    notes_audit_fees_expenses,

    -- derived growth metrics
    turnover_growth_pct,
    operating_profit_growth_pct,
    net_profit_growth_pct

FROM with_growth

